# Generated by Django 4.2.5 on 2023-09-28 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associations',
            fields=[
                ('association_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url_homepage', models.CharField(max_length=255)),
                ('main_focus', models.TextField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'associations',
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(db_comment='Herr, dr, etc', max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=255, null=True)),
                ('values', models.TextField(blank=True, db_comment='Values is what is important to me, what I would like to see in the company I work for', null=True)),
                ('desired_job', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('house_number', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number_region', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email_adress', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('linkedin_address', models.TextField(blank=True, null=True)),
                ('notice_period_days', models.IntegerField(blank=True, null=True)),
                ('earliest_start_date', models.DateField(blank=True, null=True)),
                ('employed', models.BooleanField(blank=True, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('preferred_work_percent', models.IntegerField(blank=True, null=True)),
                ('yearly_salary_expectation_chf', models.IntegerField(blank=True, db_column='yearly_salary_expectation_CHF', null=True)),
                ('avatart_url', models.CharField(blank=True, max_length=255, null=True)),
                ('accepted_privacy', models.BooleanField(blank=True, null=True)),
                ('skip_tutorial', models.BooleanField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('values', models.TextField(blank=True, db_comment='Values is what is important to the company', null=True)),
                ('main_contact_first_name', models.CharField(max_length=255)),
                ('main_contact_last_name', models.CharField(max_length=255)),
                ('main_contact_email', models.CharField(max_length=255)),
                ('main_contact_region_code', models.IntegerField(blank=True, null=True)),
                ('main_contact_phone_number', models.IntegerField(blank=True, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('accepted_privacy', models.BooleanField(blank=True, null=True)),
                ('skip_tutorial', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(db_column='invited_by', db_comment='association id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.associations')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('contry_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name_in_english', models.CharField(max_length=255)),
                ('country_name_in_native_language', models.CharField(max_length=255)),
                ('country_it_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('job_description', models.TextField()),
                ('open', models.BooleanField()),
                ('role_id', models.IntegerField()),
                ('last_day_to_apply', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='LanguagesProficiency',
            fields=[
                ('language_proficiency_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_proficiency_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'languages_proficiency',
            },
        ),
        migrations.CreateModel(
            name='PageCounts',
            fields=[
                ('page_count_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('views', models.IntegerField()),
            ],
            options={
                'db_table': 'page_counts',
                'db_table_comment': 'Stores the daily page counts statistics',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='SkillsProficiency',
            fields=[
                ('skill_proficiency_id', models.AutoField(primary_key=True, serialize=False)),
                ('proficiency_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'skills_proficiency',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_descrption', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='WorkModels',
            fields=[
                ('preferred_work_model_id', models.AutoField(primary_key=True, serialize=False)),
                ('preferred_work_model_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'work_models',
            },
        ),
        migrations.CreateModel(
            name='WorkPermits',
            fields=[
                ('work_permit_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_work_permit', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'work_permits',
            },
        ),
        migrations.CreateModel(
            name='Subsidiaries',
            fields=[
                ('subsidiary_id', models.AutoField(primary_key=True, serialize=False)),
                ('subsidiary_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.companies')),
            ],
            options={
                'db_table': 'subsidiaries',
            },
        ),
        migrations.CreateModel(
            name='SelectedCandidates',
            fields=[
                ('selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.candidates')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.jobs')),
            ],
            options={
                'db_table': 'selected_candidates',
            },
        ),
        migrations.CreateModel(
            name='SearchAlert',
            fields=[
                ('search_alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('search_alert_parameters', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.companies')),
            ],
            options={
                'db_table': 'search_alert',
                'db_table_comment': 'Placeholder',
            },
        ),
        migrations.CreateModel(
            name='PersonalityTests',
            fields=[
                ('personality_test_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.candidates')),
            ],
            options={
                'db_table': 'personality_tests',
                'db_table_comment': 'Placeholder',
            },
        ),
        migrations.AddField(
            model_name='jobs',
            name='subsidiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.subsidiaries'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_id', models.AutoField(primary_key=True, serialize=False)),
                ('validation_string', models.CharField(db_comment='String that validates if the invitation is valid', max_length=255)),
                ('company_invite', models.BooleanField(blank=True, db_comment='If it"s not a company, then it"s a candidate', null=True)),
                ('invitation_created_at', models.DateTimeField(blank=True, null=True)),
                ('association', models.ForeignKey(db_comment='Association that created the invite', on_delete=django.db.models.deletion.DO_NOTHING, to='api.associations')),
            ],
            options={
                'db_table': 'invitation',
            },
        ),
        migrations.CreateModel(
            name='Initiatives',
            fields=[
                ('initiative_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('initiative_url', models.CharField(blank=True, max_length=255, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.associations')),
            ],
            options={
                'db_table': 'initiatives',
            },
        ),
        migrations.CreateModel(
            name='CongnitiveTests',
            fields=[
                ('congnitive_test_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.candidates')),
            ],
            options={
                'db_table': 'congnitive_tests',
                'db_table_comment': 'Placeholder',
            },
        ),
        migrations.CreateModel(
            name='CompanyUsers',
            fields=[
                ('company_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_user_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('company_user_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_user_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_preferred_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('company_user_phone_number_region', models.IntegerField(blank=True, null=True)),
                ('company_user_phone_number', models.IntegerField(blank=True, null=True)),
                ('avatart_url', models.CharField(blank=True, max_length=255, null=True)),
                ('company_user_role', models.IntegerField(blank=True, db_comment='Is there a need for RBAC?', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('subsidiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.subsidiaries')),
            ],
            options={
                'db_table': 'company_users',
            },
        ),
        migrations.CreateModel(
            name='CanditatesInitiatives',
            fields=[
                ('canditates_initiatives_id', models.AutoField(primary_key=True, serialize=False)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('requested', models.BooleanField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.candidates')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.initiatives')),
            ],
            options={
                'db_table': 'canditates_initiatives',
            },
        ),
        migrations.CreateModel(
            name='CandidatesLanguage',
            fields=[
                ('candidate_language_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.candidates')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.languages')),
                ('language_proficiency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.languagesproficiency')),
            ],
            options={
                'db_table': 'candidates_language',
            },
        ),
        migrations.CreateModel(
            name='CandidatesFiles',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.candidates')),
            ],
            options={
                'db_table': 'candidates_files',
            },
        ),
        migrations.CreateModel(
            name='CandidatesAssociations',
            fields=[
                ('candidate_association_id', models.AutoField(primary_key=True, serialize=False)),
                ('assiciation_comment', models.TextField(blank=True, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.associations')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.candidates')),
            ],
            options={
                'db_table': 'candidates_associations',
            },
        ),
        migrations.AddField(
            model_name='candidates',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.countries'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='invited_by',
            field=models.ForeignKey(db_column='invited_by', db_comment='association id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.associations'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='preferred_work_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.workmodels'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='status',
            field=models.ForeignKey(blank=True, db_comment='looking for a job, open to oferings, etc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.status'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='work_permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.workpermits'),
        ),
        migrations.CreateModel(
            name='CadidatesSkill',
            fields=[
                ('candidate_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.candidates')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.skills')),
                ('skill_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.skillsproficiency')),
            ],
            options={
                'db_table': 'cadidates_skill',
            },
        ),
        migrations.CreateModel(
            name='AssociationUsers',
            fields=[
                ('association_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('association_user_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('association_user_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('association_user_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('association_user_preferred_name', models.CharField(blank=True, max_length=255, null=True)),
                ('association_user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('association_user_phone_number_region', models.IntegerField(blank=True, null=True)),
                ('association_user_phone_number', models.IntegerField(blank=True, null=True)),
                ('association_user_role', models.IntegerField(blank=True, db_comment='Is there a need for RBAC?', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.associations')),
            ],
            options={
                'db_table': 'association_users',
            },
        ),
    ]
