# Generated by Django 4.2.5 on 2023-09-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_associationusers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='association',
            field=models.ForeignKey(db_comment='Association that created the invite', on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitations', to='api.associations'),
        ),
    ]
