# Generated by Django 4.2.5 on 2023-10-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_file_name_candidatesdocuments_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResfreshToken',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('session_id', models.UUIDField()),
            ],
            options={
                'db_table': '"auth"."refresh_token"',
                'db_table_comment': 'Auth: Stores users refresh tokens.',
                'managed': False,
            },
        ),
    ]
