# Generated by Django 4.2.5 on 2023-10-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_refreshtokens_delete_resfreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('factor_id', models.UUIDField(blank=True, null=True)),
                ('aal', models.TextField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, db_comment='Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.', null=True)),
            ],
            options={
                'db_table': '"auth"."sessions"',
                'db_table_comment': 'Auth: Stores session data associated to a user.',
                'managed': False,
            },
        ),
    ]
