# Generated by Django 4.2.5 on 2023-10-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_associations_supabase_authenticaiton_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseIdToUserIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_authenticaiton_uuid', models.UUIDField()),
                ('user_id', models.IntegerField()),
                ('role', models.CharField(max_length=255)),
            ],
        ),
    ]
