# Generated by Django 4.2.5 on 2023-10-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_candidates_accepted_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='invited_by',
            field=models.ForeignKey(blank=True, db_column='invited_by', db_comment='association id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.associations'),
        ),
    ]
