# Generated by Django 4.2.5 on 2023-10-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_personality_description_candidates_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='hard_skills',
            field=models.TextField(),
        ),
    ]
