# Generated by Django 4.2.5 on 2023-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_candidates_supabase_authenticaiton_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
