# Generated by Django 4.2.5 on 2023-10-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_jobs_company_alter_jobs_hard_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='hard_skill_test_matching',
            field=models.ManyToManyField(to='api.skills'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='soft_skill_test_matching',
            field=models.ManyToManyField(to='api.softskills'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='hard_skill_test_matching',
            field=models.ManyToManyField(to='api.skills'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='soft_skill_test_matching',
            field=models.ManyToManyField(to='api.softskills'),
        ),
    ]
