"""
Django settings for shift_3_womenpp project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from rest_framework import permissions
from os import getenv, path, mkdir, environ
from pathlib import Path

from dotenv import find_dotenv, load_dotenv

ENV_FILE = find_dotenv(raise_error_if_not_found=True)

load_dotenv(ENV_FILE)

environ["DOC_EXPANSION"] = "none"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = path.join(BASE_DIR, "static/")

# Build folder for logging
if not path.exists("logs"):
    mkdir("logs")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ikvw5-1&wx-_unasd54$_&yjn-v6&n78tg9q4-b(5o&xe)vn0g"
# SECURE_SSL_REDIRECT = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    # External apps
    "rest_framework",
    "drf_spectacular",
    # Remove unused files from storage, not default Django behaviour
    "django_cleanup.apps.CleanupConfig",
    # Enable CORS
    "corsheaders",
    # Internal apps
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "shift_3_womenpp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "shift_3_womenpp.wsgi.application"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "api.authentication_services.CustomTokenAuthentication",
    ),
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": getenv("POSTGRES_DB_NAME"),
        "USER": getenv("POSTGRES_USER_NAME"),
        "PASSWORD": getenv("POSTGRES_PASSWORD"),
        "HOST": getenv("POSTGRES_HOST"),
        "PORT": getenv("POSTGRES_PORT"),
        "OPTIONS": {
            "connect_timeout": 5,
        },
    },
    # Supabase protected tables
    "auth": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": getenv("POSTGRES_DB_NAME"),
        "USER": getenv("POSTGRES_USER_NAME"),
        "PASSWORD": getenv("POSTGRES_PASSWORD"),
        "HOST": getenv("POSTGRES_HOST"),
        "PORT": getenv("POSTGRES_PORT"),
        "OPTIONS": {"connect_timeout": 5, "options": "-c search_path=auth"},
    },
    "test": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": getenv("POSTGRES_DB_NAME"),
        "USER": getenv("POSTGRES_USER_NAME"),
        "PASSWORD": getenv("POSTGRES_PASSWORD"),
        "HOST": getenv("POSTGRES_HOST"),
        "PORT": getenv("POSTGRES_PORT"),
        "OPTIONS": {
            "connect_timeout": 5,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


STORAGES = {
    "default": {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        "OPTIONS": {"bucket_name": "shift-enter"},
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# DRF Spectacular

SPECTACULAR_SETTINGS = {
    "TITLE": "Shift Enter API",
    "DESCRIPTION": "Welcome to shift enter!",
    "VERSION": "0.13",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/*",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "docExpansion ": ["full"],
    },
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "CET"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# SECURITY WARNING: All settings below will be changed in production

DEBUG = True
CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = (
    "http://localhost:3000",  # for localhost (REACT Default)
    "http://192.168.0.50:3000",  # for network
    "http://localhost:8000",  # for localhost (Developlemt)
    "http://192.168.0.50:8000",  # for network (Development)
    "https://nextjsapp-iwghenktca-ew.a.run.app",  # Deployed app
    # "https://localhost:80",
)

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",  # for localhost (REACT Default)
    "http://192.168.0.50:3000",  # for network
    "http://localhost:8000",  # for localhost (Developlemt)
    "http://192.168.0.50:8000",  # for network (Development)
    "https://nextjsapp-iwghenktca-ew.a.run.app",  # Deployed app
    # "https://localhost:80",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Project parameters

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
