# Generated by Django 4.2.5 on 2023-10-06 09:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associations',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='associations',
            name='url_homepage',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidatesdocuments',
            name='file_name',
            field=models.FileField(upload_to=api.models.CandidatesDocuments.allocate_to_candidate_folder),
        ),
        migrations.AlterField(
            model_name='initiatives',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
