# Generated by Django 4.2.5 on 2023-10-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_associations_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatesdocuments',
            old_name='file_name',
            new_name='file',
        ),
    ]
