# Generated by Django 4.2.5 on 2023-10-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sessions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sessions',
        ),
    ]
