# Generated by Django 4.2.5 on 2023-10-10 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_sessions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='refreshtokens',
            table='"auth"."refresh_tokens"',
        ),
    ]
