# Generated by Django 4.2.5 on 2023-10-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_supabaseidtouserids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supabaseidtouserids',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
