# Generated by Django 4.2.5 on 2023-10-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_supabaseidtouserids_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country_it_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country_name_in_native_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
