# Generated by Django 4.2.5 on 2023-10-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_countries_country_it_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associationusers',
            old_name='association_user_designation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='associationusers',
            old_name='association_user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='associationusers',
            old_name='association_user_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='associationusers',
            old_name='association_user_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='associationusers',
            old_name='association_user_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='associationusers',
            old_name='association_user_phone_number_region',
            new_name='phone_number_region',
        ),
        migrations.RenameField(
            model_name='associationusers',
            old_name='association_user_preferred_name',
            new_name='preferred_name',
        ),
        migrations.RenameField(
            model_name='associationusers',
            old_name='association_user_role',
            new_name='role_inside_association',
        ),
        migrations.RenameField(
            model_name='companyusers',
            old_name='company_preferred_name',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='companyusers',
            old_name='company_user_designation',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='companyusers',
            old_name='company_user_email',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='companyusers',
            old_name='company_user_phone_number',
            new_name='hone_number',
        ),
        migrations.RenameField(
            model_name='companyusers',
            old_name='company_user_phone_number_region',
            new_name='hone_number_region',
        ),
        migrations.RenameField(
            model_name='companyusers',
            old_name='company_user_first_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='companyusers',
            old_name='company_user_last_name',
            new_name='preferred_name',
        ),
        migrations.RenameField(
            model_name='companyusers',
            old_name='company_user_role',
            new_name='role_inside_company',
        ),
    ]
