# Generated by Django 4.2.5 on 2023-10-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_email_associationusers_email_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='accepted_privacy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='skip_tutorial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
