# Generated by Django 4.2.5 on 2023-10-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_companies_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='invited_by',
            field=models.ForeignKey(blank=True, db_column='invited_by', db_comment='association id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.associations'),
        ),
    ]
