# Generated by Django 4.2.5 on 2023-10-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_candidates_invited_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCompanyDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
            ],
        ),
    ]
