# Generated by Django 4.2.5 on 2023-10-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_availablecompanydomains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyusers',
            old_name='email',
            new_name='email_adress',
        ),
    ]
