# Generated by Django 4.2.5 on 2023-10-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_email_companyusers_email_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='personality_description',
            new_name='about_me',
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='email_adress',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='related_experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='city',
            new_name='location_city',
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='work_permit',
            new_name='work_permission_CH',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='country',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='desired_job',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='file_cv',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='phone_number_region',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='preferred_work_id',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='preferred_work_model',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='status',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='values_text',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='subsidiary',
        ),
        migrations.AddField(
            model_name='candidates',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='ethnicity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='hard_skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='last_country',
            field=models.ForeignKey(default=227, on_delete=django.db.models.deletion.DO_NOTHING, to='api.countries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidates',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='soft_skills',
            field=models.TextField(default=['']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='industry',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_title',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='location_country',
            field=models.ForeignKey(default=227, on_delete=django.db.models.deletion.DO_NOTHING, to='api.countries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='raw_description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='skills',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='values',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='website',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidates',
            name='accepted_privacy',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='email_adress',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='main_contact_first_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='main_contact_last_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='supabase_authenticaiton_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
