# Generated by Django 4.2.5 on 2023-10-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_candidates_hard_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='hard_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
