# Generated by Django 4.2.5 on 2023-10-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_candidates_hard_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='supabase_authenticaiton_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
