# Generated by Django 4.2.5 on 2023-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_candidates_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
