# Generated by Django 4.2.5 on 2023-10-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_candidates_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='company_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='companies',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
