# Generated by Django 4.2.5 on 2023-10-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_associations_first_name_associations_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='main_contact_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='main_contact_last_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='companies',
            name='preferred_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
