# Generated by Django 4.2.5 on 2023-10-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_skills_skill_new_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill_new_col',
        ),
    ]
