name: python auto-format
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: lgeiger/black-action@v1.0.1
        with:
          args: ". --check"
          options: "--check --verbose"
          src: "./src"
          jupyter: true
          version: "~= 22.0"