name: python auto-format
on:
  # Triggers the workflow on push to all the branches and on pull request to the "master" or the "dev" branch
  push:
  pull_request:
    branches: [ "master", "dev"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
          python -m pip install "black[jupyter]"

      - name: apply_black
        run:
          black  --verbose .

      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
          jupyter: true
          version: "~= 22.0"